name: loafer
description: "Techlyverse chat app"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^2.16.0
  firebase_messaging: ^14.7.3
  firebase_storage: ^11.4.1
  firebase_remote_config: ^4.3.3
  firebase_crashlytics: ^3.4.3
  firebase_analytics: ^10.6.3
  firebase_performance: ^0.9.3+3
  cloud_firestore: ^4.9.2
  firebase_app_check: ^0.2.1+3
  firebase_auth: ^4.12.1

  crypto: ^3.0.3
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0

  #location
  geocoding: ^2.1.1
  geolocator: ^10.1.0

  # utility
  http: ^1.1.0
  timeago: ^3.6.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  profanity_filter: ^2.0.0
  date_time_format: ^2.0.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  package_info_plus: ^5.0.1

 # UI and image
  google_fonts: ^6.1.0
  dynamic_color: ^1.6.9
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  flutter_native_splash: ^2.3.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/icon.png
  branding: assets/icons/techlyverse.png
  color_dark: "#121212"
  image_dark: assets/icons/icon.png
  branding_dark: assets/icons/techlyverse.png

  android_12:
    image: assets/icons/icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/icons/icon.png
    icon_background_color_dark: "#121212"

  web: false
